--- 
5: 
  27: 
  - Amandy
  - Jana
  - Juliana
  16: 
  - Andrzeja
  - "J\xC4\x99drzeja"
  - "Ma\xC5\x82gorzaty"
  5: 
  - Irydy
  - Tamary
  - Waldemara
  22: 
  - Emila
  - Neleny
  - Romy
  11: 
  - Igi
  - Mamerta
  - Miry
  28: 
  - Augustyna
  - Ingi
  - Jaromira
  17: 
  - Brunony
  - "S\xC5\x82awomira"
  - Wery
  6: 
  - Beniny
  - Filipa
  - Judyty
  23: 
  - Leoncjusza
  - "Micha\xC5\x82a"
  - Renaty
  12: 
  - Dominika
  - Imeldy
  - Pankracego
  1: 
  - "J\xC3\xB3zefa"
  - Lubomira
  - Ramony
  29: 
  - Benity
  - Maksymiliana
  - Teodozji
  18: 
  - Alicji
  - Edwina
  - Eryka
  7: 
  - Augusta
  - Gizeli
  - Ludomiry
  24: 
  - Joanny
  - Zdenka
  - Zuzanny
  13: 
  - Agnieszki
  - Magdaleny
  - Serwacego
  2: 
  - Longiny
  - Toli
  - Zygmunta
  30: 
  - Ferdynanda
  - Gryzeldy
  - Zyndrama
  19: 
  - Celestyny
  - Iwony
  - Piotra
  8: 
  - Kornela
  - Lizy
  - "Stanis\xC5\x82awa"
  25: 
  - Borysa
  - Magdy
  - Marii-Magdaleny
  14: 
  - Bonifacego
  - Julity
  - Macieja
  3: 
  - "Jarope\xC5\x82ka"
  - Marii
  - Niny
  31: 
  - Anieli
  - Feliksa
  - Kamili
  20: 
  - Bazylego
  - Bernardyna
  - Krystyny
  9: 
  - Grzegorza
  - Karoliny
  - Karola
  26: 
  - Eweliny
  - Jana
  - "Paw\xC5\x82a"
  15: 
  - Dionizego
  - Nadziei
  - Zofii
  4: 
  - Floriana
  - "Micha\xC5\x82a"
  - Moniki
  21: 
  - Jana
  - Moniki
  - Wiktora
  10: 
  - Antoniny
  - Izydory
  - Jana
11: 
  27: 
  - Franciszka
  - Kseni
  - Maksymiliana
  16: 
  - Edmunda
  - Marii
  - Marka
  5: 
  - Balladyny
  - "El\xC5\xBCbiety"
  - "S\xC5\x82awomira"
  22: 
  - Cecylii
  - Jonatana
  - Marka
  11: 
  - "Bart\xC5\x82omieja"
  - Gertrudy
  - Marcina
  28: 
  - Jakuba
  - Stefana
  - Romy
  17: 
  - Grzegorza
  - Salomei
  - Walerii
  6: 
  - Arletty
  - Feliksa
  - Leonarda
  23: 
  - Adeli
  - Felicyty
  - Klemensa
  12: 
  - Konrada
  - Renaty
  - Witolda
  1: 
  - Konrada
  - Seweryny
  - Wiktoryny
  29: 
  - "B\xC5\x82a\xC5\xBCeja"
  - Margerity
  - Saturnina
  18: 
  - Klaudyny
  - Romana
  - Tomasza
  7: 
  - Antoniego
  - Kaliny
  - "Przemi\xC5\x82y"
  24: 
  - Emmy
  - Flory
  - Romana
  13: 
  - Arkadii
  - Krystyna
  - "Stanis\xC5\x82awy"
  2: 
  - Bohdany
  - Henryka
  - Tobiasza
  30: 
  - Andrzeja
  - Maury
  - Ondraszka
  19: 
  - "El\xC5\xBCbiety"
  - Faustyny
  - "Paw\xC5\x82a"
  8: 
  - Klaudii
  - Seweryna
  - Wiktoriusza
  25: 
  - "El\xC5\xBCbiety"
  - Katarzyny
  - Klemensa
  14: 
  - Emila
  - Laury
  - Rogera
  3: 
  - Huberta
  - "Mi\xC5\x82y"
  - Sylwii
  20: 
  - Anatola
  - Edyty
  - "Rafa\xC5\x82a"
  9: 
  - Anatolii
  - Gracji
  - Teodora
  26: 
  - Leona
  - Leonarda
  - "Les\xC5\x82awy"
  15: 
  - Amielii
  - Idalii
  - Leopolda
  4: 
  - Albertyny
  - Karola
  - Olgierda
  21: 
  - Janusza
  - Marii
  - Reginy
  10: 
  - Leny
  - Lubomira
  - Natalii
6: 
  27: 
  - Cypriana
  - Emanueli
  - "W\xC5\x82adys\xC5\x82awa"
  16: 
  - Aliny
  - Anety
  - Benona
  5: 
  - Bonifacego
  - Kiry
  - Waltera
  22: 
  - Pauliny
  - Sabiny
  - Tomasza
  11: 
  - Barnaby
  - Benedykta
  - Flory
  28: 
  - Florentyny
  - Ligii
  - Leona
  17: 
  - Laury
  - Leszka
  - Marcjana
  6: 
  - Laury
  - Laurentego
  - Nory
  23: 
  - Albina
  - Wandy
  - Zenona
  12: 
  - Gwidona
  - Leonii
  - Niny
  1: 
  - Gracji
  - Jakuba
  - Konrada
  29: 
  - "Paw\xC5\x82a"
  - Piotra
  - Salomei
  18: 
  - "El\xC5\xBCbiety"
  - Marka
  - Pauli
  7: 
  - Ariadny
  - "Jaros\xC5\x82awa"
  - Roberta
  24: 
  - Danuty
  - Jana
  - Janiny
  13: 
  - Antoniego
  - Gracji
  - Lucjana
  2: 
  - Erazma
  - Marianny
  - Marzeny
  30: 
  - Arnolda
  - Emiliany
  - Lucyny
  19: 
  - Gerwazego
  - Protazego
  - Sylwii
  8: 
  - Ady
  - Celii
  - Medarda
  25: 
  - "\xC5\x81ucji"
  - Witolda
  - Wilhelma
  14: 
  - Bazylego
  - Elizy
  - Justyny
  3: 
  - Anatola
  - Leszka
  - Tamary
  20: 
  - Bogny
  - Rafaeli
  - "Rafa\xC5\x82a"
  9: 
  - Anny-Marii
  - Felicjana
  - "S\xC5\x82awoja"
  26: 
  - Jana
  - Pauliny
  - Rudolfiny
  15: 
  - Jolanty
  - Lotara
  - Wita
  4: 
  - Christy
  - Helgi
  - Karola
  21: 
  - Alicji
  - Alojzego
  - Rudolfa
  10: 
  - "Bogumi\xC5\x82a"
  - Diany
  - "Ma\xC5\x82gorzaty"
12: 
  27: 
  - Fabioli
  - Jana
  - "\xC5\xBBanety"
  16: 
  - Albiny
  - Sebastiana
  - "Zdzis\xC5\x82awy"
  5: 
  - Kryspiny
  - Norberta
  - Sabiny
  22: 
  - "Bo\xC5\xBCeny"
  - Drogomira
  - Zenona
  11: 
  - Biny
  - Damazego
  - Waldemara
  28: 
  - Antoniusza
  - Cezarego
  - Teofilii
  17: 
  - Jolanty
  - "\xC5\x81ukasza"
  - Olimpii
  6: 
  - Dionizji
  - Leontyny
  - "Miko\xC5\x82aja"
  23: 
  - Dagny
  - "S\xC5\x82awomiry"
  - Wiktora
  12: 
  - Ady
  - Aleksandra
  - Dagmary
  1: 
  - Blanki
  - Edmunda
  - Eligiusza
  29: 
  - Dawida
  - Dionizy
  - Tomasza
  18: 
  - "Bogus\xC5\x82awa"
  - Gracjana
  - Laury
  7: 
  - Agaty
  - Dalii
  - "Sobies\xC5\x82awa"
  24: 
  - Adama
  - Ewy
  - Irminy
  13: 
  - Dalidy
  - Juliusza
  - "\xC5\x81ucji"
  2: 
  - Balbiny
  - Ksawerego
  - Pauliny
  30: 
  - Eugeniusza
  - Katarzyny
  - Sabiny
  19: 
  - Beniaminy
  - Dariusza
  - Gabrieli
  8: 
  - Delfiny
  - Marii
  - Wirginiusza
  25: 
  - Anety
  - Glorii
  - Piotra
  14: 
  - Alfreda
  - Izydora
  - Zoriny
  3: 
  - Hilarego
  - Franciszki
  - Ksawery
  31: 
  - Mariusza
  - Melanii
  - |-
    Sylwestra
    	)
    )
  20: 
  - "Bogumi\xC5\x82y"
  - Dominika
  - Zefiryna
  9: 
  - Anety
  - Leokadii
  - "Wies\xC5\x82awa"
  26: 
  - Dionizego
  - Kaliksta
  - Szczepana
  15: 
  - Celiny
  - Ireneusza
  - Niny
  4: 
  - Barbary
  - Hieronima
  - Krystiana
  21: 
  - Honoraty
  - Seweryny
  - Tomasza
  10: 
  - Danieli
  - Bohdana
  - Julii
1: 
  27: 
  - Anieli
  - Juliana
  - "Przemys\xC5\x82awa"
  16: 
  - Marcelego
  - Walerii
  - "W\xC5\x82odzimierza"
  5: 
  - Edwarda
  - Hanny
  - Szymona
  22: 
  - Dominiki
  - Mateusza
  - Wincentego
  11: 
  - Feliksa
  - Honoraty
  - Marty
  28: 
  - Agnieszki
  - Kariny
  - "Les\xC5\x82awa"
  17: 
  - Antoniego
  - Henryki
  - Mariana
  6: 
  - Kacpra
  - Melchiora
  - Baltazara
  23: 
  - Fernandy
  - Jana
  - Rajmundy
  12: 
  - Bernarda
  - "Czes\xC5\x82awy"
  - Grety
  1: 
  - "Mas\xC5\x82awa"
  - "Mieczys\xC5\x82awa"
  - Mieszka
  29: 
  - Franciszka
  - Konstancji
  - Salomei
  18: 
  - Beatrycze
  - "Ma\xC5\x82gorzaty"
  - Piotra
  7: 
  - Juliana
  - Lucjana
  - Walentyny
  24: 
  - Felicji
  - Roberta
  - "S\xC5\x82awy"
  13: 
  - "Bogumi\xC5\x82a"
  - "Bogumi\xC5\x82y"
  - Weroniki
  2: 
  - Bazylego
  - Makarego
  - Narcyzy
  30: 
  - Martyny
  - Macieja
  - Teofila
  19: 
  - Erwiny
  - Henryka
  - Mariusza
  8: 
  - Artura
  - Rajmunda
  - Seweryny
  25: 
  - "Mi\xC5\x82osza"
  - "Paw\xC5\x82a"
  - Tatiany
  14: 
  - Feliksa
  - Hilarego
  - Martyny
  3: 
  - Arlety
  - Danuty
  - Lucjana
  31: 
  - Joanny
  - Ksawerego
  - Luizy
  20: 
  - Fabioli
  - "Mi\xC5\x82y"
  - Sebastiana
  9: 
  - Adriana
  - Alicji
  - Teresy
  26: 
  - "Lutos\xC5\x82awa"
  - Normy
  - Pauliny
  15: 
  - Arnolda
  - Dory
  - "Paw\xC5\x82a"
  4: 
  - Anieli
  - "El\xC5\xBCbiety"
  - Tytusa
  21: 
  - Agnieszki
  - "Jaros\xC5\x82awa"
  - Nory
  10: 
  - Ady
  - Jana
  - Wilhelma
7: 
  27: 
  - Aureliusza
  - Natalii
  - Rudolfa
  16: 
  - Eustachego
  - Mariki
  - Mirelli
  5: 
  - Antoniego
  - "Bart\xC5\x82omieja"
  - Karoliny
  22: 
  - Magdaleny
  - Mileny
  - "Wawrzy\xC5\x84ca"
  11: 
  - Benedykta
  - Kariny
  - Olgi
  28: 
  - Ady
  - Wiwiany
  - Sylwiusza
  17: 
  - Aleksego
  - Bogdana
  - Martyny
  6: 
  - Dominiki
  - "Jarope\xC5\x82ka"
  - "\xC5\x81ucji"
  23: 
  - "S\xC5\x82awy"
  - "S\xC5\x82awosza"
  - "\xC5\xBBelis\xC5\x82awy"
  12: 
  - Brunona
  - Jana
  - Wery
  1: 
  - Bogusza
  - Haliny
  - Mariana
  29: 
  - Marty
  - Konstantego
  - Olafa
  18: 
  - Kamila
  - Karoliny
  - Roberta
  7: 
  - Estery
  - Kiry
  - Rudolfa
  24: 
  - Kingi
  - Krystyna
  - Michaliny
  13: 
  - Danieli
  - Irwina
  - "Ma\xC5\x82gorzaty"
  2: 
  - Kariny
  - Serafiny
  - Urbana
  30: 
  - Julity
  - "Ludmi\xC5\x82y"
  - "Zdobys\xC5\x82awa"
  19: 
  - Alfreny
  - Rufina
  - Wincentego
  8: 
  - Arnolda
  - Edgara
  - "El\xC5\xBCbiety"
  25: 
  - jakuba
  - Krzysztofa
  - Walentyny
  14: 
  - Kamili
  - Kamila
  - Marcelego
  3: 
  - Anatola
  - Jacka
  - "Miros\xC5\x82awy"
  31: 
  - Ignacego
  - Lodomiry
  - Romana
  20: 
  - Fryderyka
  - "Ma\xC5\x82gorzaty"
  - Seweryny
  9: 
  - Hieronima
  - Palomy
  - Weroniki
  26: 
  - Anny
  - "Miros\xC5\x82awy"
  - Joachima
  15: 
  - Henryka
  - Igi
  - "W\xC5\x82odzimierza"
  4: 
  - Aureli
  - Malwiny
  - Zygfryda
  21: 
  - Danieli
  - "Wawrzy\xC5\x84ca"
  - Wiktora
  10: 
  - Filipa
  - Sylwany
  - Witalisa
2: 
  27: 
  - Gagrieli
  - Liwii
  - Leonarda
  16: 
  - Danuty
  - Daniela
  - Juliany
  5: 
  - Agaty
  - Filipa
  - Justyniana
  22: 
  - "Ma\xC5\x82gorzaty"
  - Marty
  - Nikifora
  11: 
  - Bernadetty
  - Marii
  - Olgierda
  28: 
  - Ludomira
  - Makarego
  - Wiliany
  17: 
  - Donata
  - Gizeli
  - "\xC5\x81ukasza"
  6: 
  - Amandy
  - Bogdana
  - Doroty
  23: 
  - Damiana
  - Romana
  - Romany
  12: 
  - "Czas\xC5\x82awa"
  - Damiana
  - Normy
  1: 
  - Brygidy
  - Dobrogniewa
  - Ignacego
  29: 
  - Lecha
  - Lutomira
  - Wiktora
  18: 
  - Konstancji
  - Krystiana
  - Sylwany
  7: 
  - Ryszarda
  - Teodora
  - Wilhelminy
  24: 
  - Boguty
  - Bogusza
  - Macieja
  13: 
  - Grzegorza
  - "Les\xC5\x82awa"
  - Katarzyny
  2: 
  - Kornela
  - Marii
  - "Miros\xC5\x82awy"
  19: 
  - Bettiny
  - Konrada
  - "Miros\xC5\x82awa"
  8: 
  - Irminy
  - Piotra
  - Sylwii
  25: 
  - Almy
  - Cezarego
  - "Jaros\xC5\x82awa"
  14: 
  - Liliany
  - Walentyny
  - Walentego
  3: 
  - "B\xC5\x82a\xC5\xBCeja"
  - Joanny
  - Telimeny
  20: 
  - Anety
  - Lecha
  - Leona
  9: 
  - Bernarda
  - Eryki
  - Rajmunda
  26: 
  - "Bogumi\xC5\x82a"
  - Eweliny
  - "Miros\xC5\x82awa"
  15: 
  - Arnolda
  - Jowity
  - Georginy
  4: 
  - Andrzeja
  - Mariusza
  - Weroniki
  21: 
  - Eleonory
  - Lenki
  - Kiejstuta
  10: 
  - Elwiry
  - Elizy
  - Jacka
8: 
  27: 
  - Cezarego
  - "Ma\xC5\x82gorzaty"
  - Moniki
  16: 
  - Joachima
  - Nory
  - Stefana
  5: 
  - Emila
  - Karoliny
  - Kary
  22: 
  - Cezarego
  - Marii
  - Zygfryda
  11: 
  - Luizy
  - "W\xC5\x82odzmierza"
  - Zuzanny
  28: 
  - Adeliny
  - Erazma
  - "Sobies\xC5\x82awa"
  17: 
  - Anity
  - Elizy
  - Mirona
  6: 
  - Jakuba
  - "S\xC5\x82awy"
  - Wincentego
  23: 
  - Apolinarego
  - "Mi\xC5\x82y"
  - "R\xC3\xB3\xC5\xBCy"
  12: 
  - Hilarii
  - Juliana
  - Lecha
  1: 
  - "Jaros\xC5\x82awa"
  - Justyny
  - Nadziei
  29: 
  - Beaty
  - Racibora
  - Sabiny
  18: 
  - "Bogus\xC5\x82awa"
  - "Bronis\xC5\x82awa"
  - Ilony
  7: 
  - Donaty
  - Olechny
  - Kajetana
  24: 
  - Bartosza
  - Jerzego
  - Maliny
  13: 
  - Elwiry
  - Hipolita
  - "Rados\xC5\x82awy"
  2: 
  - Gustawa
  - Kariny
  - Stefana
  30: 
  - Benona
  - Jowity
  - "Szcz\xC4\x99snego"
  19: 
  - Emilii
  - Julinana
  - Konstancji
  8: 
  - Izy
  - Rajmunda
  - Seweryna
  25: 
  - Belii
  - Ludwika
  - Luizy
  14: 
  - Alfreda
  - Maksymiliana
  - Selmy
  3: 
  - Augustyna
  - Kamelii
  - Lidii
  31: 
  - Cyrusa
  - Izabeli
  - Rajmundy
  20: 
  - Bernarda
  - Sabiny
  - Samuela
  9: 
  - Klary
  - Romana
  - Rozyny
  26: 
  - Ireneusza
  - Konstantego
  - Marii
  15: 
  - Marii
  - Napoleona
  - Stelli
  4: 
  - Dominiki
  - Dominika
  - Protazego
  21: 
  - Franciszka
  - Kazimiery
  - Ruty
  10: 
  - Bianki
  - Borysa
  - "Wawrzy\xC5\x84ca"
3: 
  27: 
  - Ernesta
  - Jana
  - Marka
  16: 
  - Izabeli
  - Henryka
  - Oktawii
  5: 
  - Aurory
  - Fryderyka
  - Oliwii
  22: 
  - "Bogus\xC5\x82awa"
  - Jagody
  - Katarzyny
  11: 
  - Konstantego
  - "Ludos\xC5\x82awa"
  - Rozyny
  28: 
  - Anieli
  - Kasrota
  - Soni
  17: 
  - Reginy
  - Patryka
  - Zdyszka
  6: 
  - Jordana
  - Marcina
  - "R\xC3\xB3\xC5\xBCy"
  23: 
  - Feliksa
  - Konrada
  - "Zbys\xC5\x82awy"
  12: 
  - Grzegorza
  - Justyny
  - "J\xC3\xB3zefiny"
  1: 
  - Albina
  - Antoniny
  - "Rados\xC5\x82awy"
  29: 
  - Marka
  - Wiktoryny
  - Zenona
  18: 
  - Edwarda
  - Narcyza
  - "Zbys\xC5\x82awa"
  7: 
  - Flicyty
  - Kajetana
  - Pauli
  24: 
  - Gabrieli
  - Marka
  - Seweryna
  13: 
  - "Bo\xC5\xBCeny"
  - Krystyny
  - Marka
  2: 
  - Halszki
  - Heleny
  - Karola
  30: 
  - Amelii
  - Dobromira
  - Leonarda
  19: 
  - Aleksandryny
  - "J\xC3\xB3zefa"
  - Nicety
  8: 
  - Beaty
  - Juliana
  - Wincentego
  25: 
  - Bolka
  - Cezaryny
  - Marioli
  14: 
  - Dalii
  - Leona
  - Matyldy
  3: 
  - Kingi
  - Maryna
  - Tycjana
  31: 
  - Balbiny
  - Kamila
  - Kornelii
  20: 
  - Joachima
  - Kiry
  - Maurycego
  9: 
  - Dominika
  - Franciszki
  - Katarzyny
  26: 
  - Dory
  - Olgi
  - Teodora
  15: 
  - Delfiny
  - Longina
  - Ludwiki
  4: 
  - Adrianny
  - Kazimierza
  - "Wac\xC5\x82awa"
  21: 
  - Benedykta
  - Lubomiry
  - Lubomira
  10: 
  - "Bo\xC5\xBCys\xC5\x82awy"
  - Cypriana
  - Marcelego
9: 
  27: 
  - Damiana
  - Mirabeli
  - Wincentego
  16: 
  - Jagienki
  - Kamili
  - Korneliusza
  5: 
  - Doroty
  - Justyna
  - "Wawrzy\xC5\x84ca"
  22: 
  - Maury
  - Milany
  - Tomasza
  11: 
  - Dagny
  - Jacka
  - Prota
  28: 
  - Libuszy
  - "Wac\xC5\x82awy"
  - "Wac\xC5\x82awa"
  17: 
  - Franciszka
  - Lamberty
  - Narcyza
  6: 
  - Beaty
  - Eugeniusza
  - Lidy
  23: 
  - "Bogus\xC5\x82awa"
  - Liwiusza
  - Tekli
  12: 
  - Amadeusza
  - Gwidy
  - Sylwiny
  1: 
  - Belindy
  - Bronisza
  - Idziego
  29: 
  - Michaliny
  - "Micha\xC5\x82a"
  - "Rafa\xC5\x82a"
  18: 
  - Ireny
  - Irminy
  - "Stanis\xC5\x82awa"
  7: 
  - Reginy
  - Marka
  - Melchiora
  24: 
  - Dory
  - Gerarda
  - Maryny
  13: 
  - Apolinarego
  - Eugenii
  - Lubomira
  2: 
  - Dionizy
  - Izy
  - Juliana
  30: 
  - Geraldy
  - Honoriusza
  - Wery
  19: 
  - Januarego
  - Konstancji
  - Leopolda
  8: 
  - Czcibora
  - Marii
  - "Rados\xC5\x82awa"
  25: 
  - Aureli
  - Kamila
  - Kleofasa
  14: 
  - Bernarda
  - Mony
  - Roksany
  3: 
  - Joachima
  - Liliany
  - Szymona
  20: 
  - Eustachego
  - Faustyny
  - Renaty
  9: 
  - Aldony
  - Jakuba
  - Sergiusza
  26: 
  - Cypriana
  - Justyny
  - "\xC5\x81ucji"
  15: 
  - Albina
  - Lolity
  - Ronalda
  4: 
  - Dalii
  - Idy
  - Rocha
  21: 
  - Darii
  - Mateusza
  - "Wawrzy\xC5\x84ca"
  10: 
  - Eligii
  - Irmy
  - "\xC5\x81ukasza"
4: 
  27: 
  - Sergiusza
  - Teofila
  - Zyty
  16: 
  - Bernarda
  - Biruty
  - Erwina
  5: 
  - Ireny
  - Kleofasa
  - Wincentego
  22: 
  - "\xC5\x81ukasza"
  - Kai
  - Nastazji
  11: 
  - Filipa
  - Izoldy
  - Leona
  28: 
  - Bogny
  - Walerii
  - Witalisa
  17: 
  - Anicety
  - Klary
  - Rudolfina
  6: 
  - Ady
  - Celestyny
  - Ireneusza
  23: 
  - Ilony
  - Jerzego
  - Wojciecha
  12: 
  - Juliusza
  - "Lubos\xC5\x82awa"
  - Wiktoryny
  1: 
  - Chryzamtyny
  - "Gra\xC5\xBCyny"
  - Zygmunta
  29: 
  - Hugona
  - Piotra
  - Roberty
  18: 
  - Apoloniusza
  - "Bogus\xC5\x82awy"
  - "Go\xEF\xBF\xBDcis\xC5\x82awy"
  7: 
  - Donata
  - Herminy
  - Rufina
  24: 
  - Bony
  - Horacji
  - Jerzego
  13: 
  - Artemona
  - Justyny
  - "Przemys\xC5\x82awy"
  2: 
  - Franciszka
  - Malwiny
  - "W\xC5\x82adys\xC5\x82awa"
  30: 
  - Balladyny
  - Lilli
  - Mariana
  19: 
  - Alfa
  - Leonii
  - Tytusa
  8: 
  - Amadeusza
  - Cezaryny
  - Juliany
  25: 
  - "Jaros\xC5\x82awa"
  - Marka
  - Wiki
  14: 
  - Bernarda
  - Martyny
  - Waleriana
  3: 
  - Pankracego
  - Renaty
  - Ryszarda
  20: 
  - Agnieszki
  - Amalii
  - Czecha
  9: 
  - Mai
  - Marcelego
  - Wadima
  26: 
  - Marii
  - Marzeny
  - Ryszarda
  15: 
  - Adolfiny
  - Odetty
  - "Wac\xC5\x82awa"
  4: 
  - Benedykta
  - Izodory
  - "Wac\xC5\x82awy"
  21: 
  - "Jaros\xC5\x82awa"
  - Konrada
  - Selmy
  10: 
  - "Borys\xC5\x82awy"
  - makarego
  - "Micha\xC5\x82a"
10: 
  27: 
  - Iwony
  - Noemi
  - Szymona
  16: 
  - "Ambro\xC5\xBCego"
  - Florentyny
  - "Gaw\xC5\x82a"
  5: 
  - Flawii
  - Justyna
  - Rajmunda
  22: 
  - Haliszki
  - Lody
  - "Przybys\xC5\x82awa"
  11: 
  - Aldony
  - Brunona
  - Emila
  28: 
  - Narcyza
  - Serafina
  - Wioletty
  17: 
  - Antonii
  - Ignacego
  - Wiktora
  6: 
  - Artura
  - Fryderyki
  - Petry
  23: 
  - Edwarda
  - Marleny
  - Seweryna
  12: 
  - Krystyny
  - Maksa
  - Serafiny
  1: 
  - Heloizy
  - Igora
  - Remigiusza
  29: 
  - Angeli
  - "Przemys\xC5\x82awa"
  - Zenobii
  18: 
  - Hanny
  - Klementyny
  - "\xC5\x81ukasza"
  7: 
  - Krystyna
  - Marii
  - Marka
  24: 
  - Arety
  - Marty
  - Marcina
  13: 
  - Edwarda
  - Geraldyny
  - Teofila
  2: 
  - Racheli
  - "S\xC5\x82awy"
  - Teofila
  30: 
  - Augustyny
  - "\xC5\x81ukasza"
  - Urbana
  19: 
  - Michaliny
  - "Micha\xC5\x82a"
  - Piotra
  8: 
  - Brygidy
  - Loreny
  - Marcina
  25: 
  - Ingi
  - Maurycego
  - Sambora
  14: 
  - Alany
  - Damiana
  - Liwii
  3: 
  - "Bogumi\xC5\x82a"
  - Gerarda
  - "J\xC3\xB3zefy"
  31: 
  - Krzysztofa
  - Augusta
  - Saturnina
  20: 
  - Ireny
  - Kleopatry
  - Witalisa
  9: 
  - Arnolda
  - Ludwika
  - Sybili
  26: 
  - Ewarysta
  - Lucyny
  - "Lutos\xC5\x82awy"
  15: 
  - Jadwigi
  - Leonarda
  - Teresy
  4: 
  - Edwina
  - "Ros\xC5\x82awy"
  - Rozalii
  21: 
  - Celiny
  - Hilarego
  - Janusza
  10: 
  - Franciszka
  - Loretty
  - Poli
